### ISSUE TITLE
Bot not saving posts from account into database

### ISSUE THREAD

**Issue by jshholland** [Lynnesbian/FediBooks#21] opened 2019-09-16 11:20 UTC
**What happened?**
My FediBooks bot shows '0 posts in database' for the user it is set to learn from, although it (@josh@squ.alid.pw) has posted lots publicly since the bot was created (is it supposed to look at the timeline retroactively too?). I've tried setting the bot and account active and inactive, deleting and re-adding the account to learn from, but nothing's helped. I gave it a few days to see if it just needed more material to learn from, but the lack of any posts in database seems concerning to me.

**How did it happen?**
1. create bot
2. add user account to learn from
3. wait

**Where did it happen?**
https://fedibooks.com/bot/accounts/@joshbot@squ.alid.pw

**Expected behavior**
Bot starts saving posts, learning from them and eventually posting.

**Error message**
No error message.

**Comment by ibrokemypie** [comment] 2019-09-17 04:24
Same here, bot "learning" from four accounts for a few days, zero posts stored for any

**Comment by Lynnesbian** [comment] 2019-09-17 08:15
This is hopefully fixed now, although there seems to be another weird issue where it only finds a small amount of posts. It's scraping the outbox files, which should contain all of a user's public posts. However, if you check https://squ.alid.pw/users/josh/outbox, there are only nine posts... I have no idea how to fix this, because FediBooks relies on the outbox, and if posts don't appear there, then it can't learn from them.

**Comment by Lynnesbian** [comment] 2019-09-17 08:17
I've confirmed this is definitely fixed, feel free to reopen if it's not working for you.

**Closed as completed by Lynnesbian** 2019-09-17 08:17 UTC
Labels: bug

**Comment by jshholland** [comment] 2019-09-17 10:25
Yep it's working for me now.

From what I can tell, Pleroma only gives the last 10 posts in the outbox. Whether this conforms to the spec or not I don't know, but maybe it's worth eventually adding some logic that follows the `next` link (adding a `max_id` query param)?

**Comment by Lynnesbian** [comment] 2019-09-17 10:27
FediBooks does follow the `next` link, but it seemingly returns the same data. On Mastodon instances it follows the `prev` link instead, which does the same thing in reverse order (showing newer posts instead of later ones). The behaviour works for Mastodon, but Pleroma seems not to give any more information from the `next` link.
